---
- name: Install Nginx and Create a File
  hosts: all
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create a File
      copy:
        content: "Hello, this is a sample file created by Ansible."
        dest: /tmp/sample_file.txt
